name: tohydamogml
channels:
  - conda-forge
  - esri
dependencies:
    - python>3.8
    - gdal=2.4.1
    - pyproj>2
    - geopandas>=0.10.0
    - jupyter
    - ipython
    - matplotlib
    - tqdm
    - scipy
    - pillow
    - lxml
    - fire
    - rasterio
    - rasterstats
    - arcgis

